# Generated by Django 4.2.11 on 2024-04-08 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_usuario',
            fields=[
                ('ID_TIPO_USUARIO', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id tipo usuario')),
                ('DESCRIPCION', models.CharField(max_length=15, verbose_name='Nombre tipo usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('ID_USUARIO', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id usuario')),
                ('NOMBRE', models.CharField(max_length=50, verbose_name='Nombre del usuario')),
                ('CORREO', models.EmailField(max_length=254, verbose_name='Correo electronico')),
                ('PASSWORD', models.CharField(max_length=50, verbose_name='Contraseña')),
                ('ID_TIPO_USUARIO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.tipo_usuario', verbose_name='Tipo de usuario')),
            ],
        ),
    ]
